### PR TITLE
add images to readme

### PR DESCRIPTION
**Pull request by Jojain**
move images in example/images folder + add images for all the workings examples (except numpy.py) + add the images in the readme.md file

### CODE REVIEW

**Comment by jmwright** [comment]
@Jojain Is this still WIP? There's code commented out in tray.py and I don't see the changes to add the images to the readme.

**Comment by Jojain** [comment]
Indeed I somehow didn't uploaded the readme file.
I uncommented the code that was left and now it shoud be finished.

**Comment by jmwright** [comment]
@Jojain Did you use the HTML tag instead of the markdown tag so that you could make the image widths consistent?

**Review by jmwright — APPROVED** [review]
Thanks @Jojain !

**Pull request merged**
