### PR TITLE
Laser-cut tray example

### PR DESCRIPTION
**Pull request by adam-urbanczyk**
Manual assy example + export to DXF for laser cutting.

obraz

### CODE REVIEW

**Comment by adam-urbanczyk** [comment]
How do we normally merge code in this repo @jmwright ?

**Comment by jmwright** [comment]
I can review it if you want, but I think for this repo if you have commit access you can feel free to merge on your own. It's supposed to be a low friction way to share things that might be useful to the broader community.

We need to add a TOC for the examples in the README. I may try to do that later today.

**Comment by adam-urbanczyk** [comment]
OK, I'll just merge.

**Comment by jmwright** [comment]
@adam-urbanczyk FYI - I added a TOC to the readme.

**Pull request merged**
